# Generated by Django 3.2.9 on 2021-11-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_institution_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='year_founded',
            field=models.PositiveIntegerField(),
        ),
    ]
