# Generated by Django 3.2.9 on 2021-11-16 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_institution_year_founded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='motto',
            new_name='vision',
        ),
    ]
